version: '3'
services:
  mosquitto:
    image: eclipse-mosquitto:1.6
    ports:
      - '1883:1883'
    volumes:
      - ./volumes/mosquitto/data:/mosquitto/data
      - ./volumes/mosquitto/log:/mosquitto/log
      - ./resources/mosquitto.conf:/mosquitto/config/mosquitto.conf

  collector:
    build:
      context: collector
    depends_on:
      - "mosquitto"
    command: [ "consume" ]
    environment:
      LOG_LEVEL: "debug"
      MQTT_HOST: "tcp://mosquitto:1883"
